services:
  django:
    build: .
    command: sh -c "python manage.py collectstatic --noinput && gunicorn --bind 0.0.0.0:8000 todo.wsgi:application"
    volumes:
      - .:/app
      - static_data:/app/static
    ports:
      - "8081:8000"

  nginx:
    image: nginx:latest
    ports:
      - "8082:80"
      - "8444:443"
    volumes:
      - static_data:/var/www/html/static
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

volumes:
  static_data:
